version: "3.9"

services:
  #web-app:
  #  build: .
  #  deploy:
  #    replicas: 2
  web-app-1:
    build: .
    ports:
      - 8081:8080
  web-app-2:
    build: .
    ports:
      - 8082:8080
  load-balancer:
    build:
      context: load-balancer
      args:
        role: master
    #ports:
    #  - 8080:8080
    cap_add:
      - NET_ADMIN
  load-balancer-2:
    build:
      context: load-balancer
      args:
        role: backup
    #ports:
    #  - 8081:8081
    cap_add:
      - NET_ADMIN
  reverse-proxy:
    build:
      context: reverse-proxy
    ports:
      - 8080:8080
networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
